h_efficient_agent:
  spy_agent: ["Agent[0.5, 0.5]", "Agent[1.5, 1.5]", "Agent[2.5, 2.5]"]
  nice_agent: ["Agent[1.5, 0.5]", "Agent[2.5, 0.5]"]
  agreeing_agent: ["Agent[0.5, 1.5]", "Agent[0.5, 2.5]"]
  critic_agent: ["Agent[1.5, 2.5]", "Agent[2.5, 1.5]"]

attitude_def:
  nice_agent: "Be very easy going. Try to find agreement with the central ageent if you can, the goal is to resolve conversation."
  critic_agent: "Be very critical and try to propose many changes."
  agreeing_agent: "Be super coopertaive, agree to whatever the central agent says directly."
