h_efficient_agent:
  spy_agent: ["Agent[0.5, 0.5]", "Agent[1.5, 1.5]", "Agent[2.5, 2.5]"]
  nice_agent: ["Agent[1.5, 0.5]", "Agent[2.5, 0.5]"]
  critic_agent: []
  agreeing_agent: []

h_efficient_standard:
  spy_agent: []
  nice_agent: ["Agent[1.5, 0.5]", "Agent[2.5, 0.5]"]
  critic_agent: []
  agreeing_agent: []

d_efficient_standard:
  spy_agent: ["Agent[0.5, 0.5]", "Agent[1.5, 1.5]", "Agent[2.5, 2.5]"]
  nice_agent: ["Agent[1.5, 0.5]", "Agent[2.5, 0.5]"]
  critic_agent: []
  agreeing_agent: []

attitude_def:
  nice_agent: "Be very easy going. Try to find agreement with the central ageent if you can, the goal is to resolve conversation."
  critic_agent: "Be very critical and try to propose many changes"
  agreeing_agent: "Be super coopertaive, agree to whatever the central agent says directly."

